### ISSUE TITLE
Module not available on Forge even if installed

### ISSUE THREAD

**Issue by Ghilteras** [silvative/pf2e-exploration-effects#1]
I have this module installed in Forge but when I boot my world and tap on Manage Modules the module is not on the list, I tired uninstalling it and reinstalling, nothing. I also tried to install it from the Foundry UI instead of Forge and the module installs but then it still shows as not installed

**Comment by silvative** [comment]
Hey, I can definitely look into this. Can you confirm your version? I think it may be because I updated the module to V10, but I am not competent enough to have two versions so that Foundry can find the V9 version if you are on V9. 

I might be able to do more work to make the module work on V9. It's something I would like to look into but I have limited time at the moment and it will resolve itself when everyone moves over to V10.

**Comment by mistamichal** [comment]
This is going to seem like a really stupid question, so I apologise in advance: Did you try stopping and then restarting the server on your game management page? I installed this mod and it didn't show up until I did a restart.

**Comment by Ghilteras** [comment]
Looks like this was just a Foundry shenanigan, I just restarted the server and now I can see the module again. We can close this.
