### ISSUE TITLE
Suggestion: Is there a way to translate it?

### ISSUE THREAD

**Issue by LiyuNodream** [silvative/pf2e-exploration-effects#5]
I noticed that the Foundry Hub - Weblate do really good these days, is there a way to put this module on the weblate? I really want to translate this module, but I dont know how to do it in code. If you can consider this suggestion, I really appreciate it.

**Comment by silvative** [comment]
The module contains almost no text at all, so I'm not actually sure how you would translate it.  I'm not against the idea of a PR for improved localization support if someone else does it, but it's not something I have time to automate or integrate, especially because of how tiny the module is- it's probably easier for users to just rename the small number of included effects instead.
