### ISSUE TITLE
Installation links all link to master branch

### ISSUE THREAD

**Issue by natis1** [silvative/pf2e-exploration-effects#7]
The installation links of the older versions of this module all link to the master branch:
https://foundryvtt.com/packages/pf2e-exploration-effects

This is bad record keeping as it means these older versions are not preserved and are impossible to download. It also means git pushing causes the module to silently update without any actual version number change. which may lead to things in the newest version of the program breaking just by git pushing.

**Comment by Axion741** [comment]
I've too have found that I can't use any version of this module with Foundry v10. All links point to the newest v11 build.

Hopefully @silvative can rectify this soon?

**Comment by silvative** [comment]
I've updated the manifest links on the admin page of the Foundry website to hopefully point to separately tagged releases from now on. I also went back and found the last stable V9 and V10 releases and made sure those were tagged appropriately so that users with older versions of Foundry can use them. 

If this isn't fixed yet, then I've done something wrong- please let me know / post another issue and I'll try to fix it.
